name: SUWIKI CI (with Gradle)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - feature/*
      - refactor/*
      - fix/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash