name: SUWIKI CI/CD with Gradle, Github Actions

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Gradle 캐싱
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: 빌드 권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: 프로젝트 빌드
        run: ./gradlew bootJar
        shell: bash

      - name: API EC2 인스턴스 접속 및 실행 중인 애플리케이션 종료
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo `sudo fuser 8080/tcp`
            sudo fuser -k 8080/tcp

      - name: API 빌드 파일 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/suwiki-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu"

      - name: API EC2 인스턴스 접속 및 애플리케이션 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo cd /home/ubuntu
            sudo ./start.sh

            ## 서버 헬스 체크
            TARGET_URL=localhost PORT=8080

            for RETRY_COUNT in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
              echo "> #${RETRY_COUNT} trying..."
              RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" $TARGET_URL:$PORT/health)

              if [ "${RESPONSE_CODE}" -eq 200 ]; then
                echo "> New WAS successfully running"
                exit 0
              elif [ ${RETRY_COUNT} -eq 10 ]; then
                echo "> Health check failed."
                exit 1
              fi
              sleep 10
            done
